### ISSUE TITLE
link for "HEDA Settings" no longer exists after new install

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#116]
On a fresh install of HEDAP, the link with text "HEDA Settings" no longer appears on the page at /home/showAllTabs.jsp nor in the menu tabs.

**Comment by ceiroa** [comment]
@chrismcmahon ~ Does this get fixed if you enable My Domain (http://releasenotes.docs.salesforce.com/en-us/winter16/release-notes/rn_lightning_cruc.htm)?

If not, is the tab available for the profile?

**Comment by chrismcmahon** [comment]
My Domain is enabled. Full URL is https://browsertests-dev-ed.my.salesforce.com/home/showAllTabs.jsp

The tab setting is simply gone. See screen shot of the System Administrator role Tab Settings.

This is as of Nov 20. 
![screen shot 2015-11-23 at 9 01 23 am](https://cloud.githubusercontent.com/assets/204643/11341701/e6b31c92-91c0-11e5-8ff2-a8936d4ac87c.png)

**Comment by ceiroa** [comment]
I see what happened. It's actually beta version 1 that is now installed in that org:

![screen shot 2015-11-23 at 10 55 07 am](https://cloud.githubusercontent.com/assets/1894238/11343343/3ee191e0-91d1-11e5-8854-2590b8eaee07.png)

I created the first production version of the package on Friday afternoon. I did this from a new packaging org in order to have a new (final prefix). This seems to have caused the installer to think beta version 1 from the old packaging org is the latest, and thus the one to install in the browser-tests org.

@jlantz ~ Let's get together to fix this.

**Comment by chrismcmahon** [comment]
After installing 'heda', Settings page exists but is blank. See screen shots

![screen shot 2015-11-23 at 11 38 00 am](https://cloud.githubusercontent.com/assets/204643/11345842/d62ba9dc-91d6-11e5-823a-2a860c8edaa1.png)
![screen shot 2015-11-23 at 11 38 18 am](https://cloud.githubusercontent.com/assets/204643/11345848/e25029a4-91d6-11e5-8516-85c480c4bb7a.png)

**Comment by chrismcmahon** [comment]
Uninstalling HEDAP Packaging 4 fixed the Settings page
