### ISSUE TITLE
Some tests fail with Dupe Management on

### ISSUE THREAD

**Issue by tet3** [SalesforceFoundation/HEDAP#190]
On a deployCI into a new Spring '16 Dev Org, several tests fail with dupe alerts, which are on by default for new orgs in Spring '16 and later. Should those tests' `insert`s use a [DMLOptions.DuplicateRuleHeader](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_class_Database_DMLOptions_DuplicateRuleHeader.htm#apex_class_Database_DMLOptions_DuplicateRuleHeader) as discussed in [this SFSE Q&A](http://salesforce.stackexchange.com/questions/78670/disable-duplicate-check-for-apex-class)?

**Comment by ceiroa** [comment]
Thanks for helping us keep this in the radar. We have reported this to platform and are waiting to hear back. It's quite possible they revert having dupe rules on by default in new orgs since this breaks existing implementations.

**Comment by ceiroa** [comment]
We have to see if changing the data in the tests fixes the problem. Otherwise we can try using  DMLOptions.DuplicateRuleHeader. If we still have failures, we'll need to add to the documentation that these rules need to be disabled (probably in the installation guide).

NPSP also looked into this (https://github.com/SalesforceFoundation/Cumulus/issues/1363), and we should investigate their approach.

Also, important, we should decide whether we want them enabled or disabled in the template.

**Comment by ceiroa** [comment]
Also referenced in #252.

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003oy12AAA" target="_blank">W-010573</a>

**Comment by ceiroa** [comment]
Two classes had failing tests:
- CON_Preferred_TEST
- ADDR_Addresses_TEST

I fixed the issues in the first one, but there's no point in trying to fix those in the second one until we merge #255. Those changes may fix some of these issues, and even if they don't, too many conflicts will result if we make any changes to that file in a different branch.

**Comment by ceiroa** [comment]
Standard Contact and Lead Matching Rule docs: https://help.salesforce.com/htviewhelpdoc?err=1&id=matching_rules_standard_contact_rule.htm&siteLang=en_US

**Comment by jlantz** [comment]
Included in beta release 1.15 (Beta 4)

**Comment by mrbelvedere** [comment]
Included in production release version 1.15
