### ISSUE TITLE
CCON_ConnectionBackfill_TEST.checkBackfillSuccess must check if the record types are available to the running user

### ISSUE THREAD

**Issue by paulmalenke** [SalesforceFoundation/HEDAP#307]
CCON_ConnectionBackfill_TEST.checkBackfillSuccess checks if 3 record types exist in order to run but it does not check that the 3 record types are actually available to the running user('System Administrator'). This test should check that they are available before running the test or else the record types will not be available for full assignment and it will fail.

**Comment by paulmalenke** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000003uV5vAAE" target="_blank">W-011201</a>

**Comment by ceiroa** [comment]
This work item was created while we were trying to get a release out and the test was failing. The issue was resolved in another way and this test failing led us to that other resolution so the test failing was good. Fixing the test in this way would cause a false positive because the real issue was namespacing. Closing story.
