### ISSUE TITLE
Course Connection: no way to discern a Faculty CC record from a Student CC record

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/HEDAP#312]
Users may create a Student or Faculty Course Connection

![screen shot 2016-08-31 at 3 56 57 pm](https://cloud.githubusercontent.com/assets/204643/18149200/bb6f1584-6f93-11e6-8eb2-c08de7f20051.png)

Having created the Course Connection record, there is no way to tell a Student CC record from a Faculty CC record without tracking down the status of the Contact. The nature of CC record Student or Faculty should be visible on the CC record.

**Comment by ceiroa** [comment]
Totally agree, but since the record types are unmanaged we cannot package the layout change. We will need to tell the users to add it to the layout and to the related lists in the installation instructions. I believe Paul already has a note for this regarding the docs. Does that sound right, @paulmalenke?

**Comment by ceiroa** [comment]
The column is there in the layout's related list in the Trial. There's nothing for us to do in the package, since we cannot make layout changes related to record types that are unmanaged.
