### ISSUE TITLE
Consider using sObjectType and Apex class references in TDTM token constructor

### ISSUE THREAD

**Issue by dospromptman** [SalesforceFoundation/HEDAP#327]

**Comment by ceiroa** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x800000048wicAAA" target="_blank">W-011641</a>

**Comment by ceiroa** [comment]
I was thinking about this, and got to the conclusion that it might be better to leave it as a string, because this way we don't have to worry about the class prefix. That is, a third-party package with prefix xxx could just store the info as xxx.myclass in the field, and everything would work. If we were to change it to a type we would need to store the prefix separately.

**Comment by paulmalenke** [comment]
I know we talked about this is a meeting but I will comment here also. I agree that we should leave this as is and not convert. It would create more complexity that can be avoided.
