### ISSUE TITLE
Support Ethnicity and Race fields as determined by NCES and IPEDS requirements

### ISSUE THREAD

**Issue by wongmike** [SalesforceFoundation/HEDAP#363]
NCES and IPEDS standards can be found here:
https://nces.ed.gov/statprog/2002/std1_5.asp
https://nces.ed.gov/ipeds/Section/collecting_re

Given I am a SFDC user
And I need to enter Ethnicity and Race information for a contact
When I Go to Enter Ethnicity
Then I can specify "Hispanic or Latino" or "Not Hispanic or Latino"
When I go enter Race
Then I can specify "American Indian or Alaskan Native", "Asian", "Black or African American", "Native Hawaiian or Other Pacific Islander", or "White"

**Comment by wongmike** [comment]
** lurch: add

**Comment by wongmike** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004RBW7AAO" target="_blank">W-017337</a>

**Comment by wongmike** [comment]
FYI, the race and ethnicity standards are evolving and we may have to revisit this again at a later date.

**Comment by Btibert3** [comment]
I was just searching for this, and wanted to say thank you for implementing this; it was the first thing that I looked for in a newly installed org. +100

**Comment by Btibert3** [comment]
If you look at point 5 at the URL below, institutions are federally required to aggregate the data for reporting purposes using those 9 categories, which includes the two question format addressed by this ticket.  Having said that, many institutions use the 9 category format for all reports on a daily basis, well before their Institutional Research department compiles the data for Federal reporting.

With the two question format, is the suggested method to track this for an institution to create a custom field with logic to combine the two-question format along with the Citizenship field into one master, official, reporting field? 

https://www2.ed.gov/policy/rschstat/guid/raceethnicity/questions.html

**Comment by jacebryan** [comment]
To answer your question: The reporting of Race and Ethnicity is up to each individual institutions requirements. Always a good question to post to the Registrar. However, your idea is definitely one of doing that :)

Also - You do have access to the Power of US Hub - I just found your profile. Looks like you are already a member of the HEDA User Group there too.

You need to log out of your Developer org in order to access the Power of US Hub from your Production org. 

Questions like this should be posted in the Power of US Hub HEDA User Group so you can benefit from the community and their helpful responses.

**Comment by Btibert3** [comment]
I will keep that in mind.  I was hoping to stay independent (dev org) in the case I branch out on my own or leave my company, but in the short run I will use my current org.

**Comment by Btibert3** [comment]
And just to follow up, my current login for my current employer, not a Salesforce.org client, has asked to join the HEDA group on Success, but that is pending, as I am no long with my former institution.
