### ISSUE TITLE
ACCT_IndividualAccount_TDTM reentrant flags limits size to 200

### ISSUE THREAD

**Issue by kyleschmid** [SalesforceFoundation/HEDAP#472]
The reentrant flags that were implemented in ACCT_IndividualAccount_TDTM since version 1.37 are limiting the amount of Contacts that this trigger runs on to 200. Since triggers operate in batch sizes of 200 and these flags get set the first time the class runs, it doesn't run for any Contacts after the first 200. Steps to reproduce:

1. Open execute anonymous window
2. Run the following (expected behavior is 300 new Contacts getting created with Administrative Accounts):
`
List<Contact> cons = new List<Contact>();
for (Integer i = 0; i < 300; i++) {
    cons.add(new Contact(LastName = 'test ACCT_IndividualAccount_TDTM reentrant flag'));
}
insert cons;
`
3. Execute the following query in the query editor:
`
SELECT Id FROM Contact WHERE AccountId = null AND LastName = 'test ACCT_IndividualAccount_TDTM reentrant flag'
`
4. Notice there's 100 Contacts with no Account

This is a big issue with anyone using the Bulk API for an integration or Data Loader.

**Comment by kevinswiggum** [comment]
Hi @kyleschmid 

Thanks for bringing attention to this issue. I work with @jacebryan on the HEDA team and wanted to let you know how we're addressing the problem (along with some additional context). 

The problem you’re seeing with this trigger handler is part of an overarching issue we’ve been addressing internally. In general, Apex triggers have the potential to fire multiple times on one or more records in a single transaction. This is especially true when additional workflow field updates or process builder updates are applied in the same transaction (record gets saved -> trigger fires -> workflow updates a field on the record -> trigger fires again). In those situations, it’s important we make sure the triggered code only executes once so that we’re not creating more than one Administrative Account for a contact.

To do so, we have static flags in place telling a trigger that it’s already been fired. That generally works well in situations where records are saved in batches of 200 or less because our “already fired” flags get reset between each batch (each batch is a separate transaction). However, the “already fired” flag methodology fails when records are updated in batches larger than 200. Behind the scenes, that large group of records is still getting split into smaller batches of 200 during the DML operation…but this time it’s all happening in the same transaction and our “already fired” flags don’t get reset. The second batch of 200 records is saved but the trigger still thinks it already fired.

The good news is we’ve been actively working on a modified solution that still prevents the trigger from firing multiple times AND handles how DML operations break up large data volumes. This should correct the behavior you’re seeing with Administrative Accounts along with any similar issues that could arise with the other TDTM trigger handlers.

**Comment by kyleschmid** [comment]
Awesome, thanks!

**Comment by kyleschmid** [comment]
Any word on when this issue will be resolved?

**Comment by kbangsberg** [comment]
Hi Kyle - it's in active development (see pull request reference above).   We don't have a solid ETA yet but hope to have an update or resolution soon.

**Comment by mrbelvedere** [comment]
Included in beta release 1.44 (Beta 2)

**Comment by cpolcyn** [comment]
Included in production release rel/1.44
