### ISSUE TITLE
Shield: Unit Test SOQL queries in HEDA are limiting the ability for certain fields to be encrypted

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/HEDAP#650]
There are a number of HEDA unit tests with SOQL queries that break (hinder) platform encryption. As a general rule, if a field is to be encrypted using Shield, the field cannot be used as a filter in a WHERE clause nor can it be used in an ORDER BY clause. Since these queries are in TEST classes, it should be fairly easy to modify the queries to eliminate use of those fields.

The affected fields and test classes are:

_Standard fields_
- *Account.Name*
    -     ADDR_HouseholdAcc_TEST, line 2181
    -     ADDR_OtherAcc_TEST, line 107, 111, 154, 159
    -     AFFL_ContactAccChange_TEST, line 71, 107, 125, 126, 150, 151, 176
    -     AFFL_MultiRecordType_TEST, line 284
- *Contact.Name*
    -     ADDR_Contact_TEST, line 980, 984, 1026, 1031
    -     AFFL_ContactAccChange_TEST, line 74, 75, 106, 124, 148, 175
    -     CON_Preferred_TEST, line 57, 99
- *Contact.Email*
    -     CON_Email_TEST, line 105

_HEDA Fields_

- *Address.MailingStreet* is referenced  in SOQL queries in HEDA unit test code
   -     ADDR_HouseholdAcc_TEST
- *Course.Description* is referenced  in SOQL queries in HEDA unit test code
   -     COUR_DescriptionCopy_TEST
   -     STG_Courses_TEST
- *Course_Offering.SectionID* is in SOQL queries in HEDA unit test code
   -     TERM_CourseOff_TEST, line 94

**Comment by kevinswiggum** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000007fOPfAAM" target="_blank">W-028915</a>

**Comment by lifewithryan** [comment]
@kevinswiggum -- I found all of the instances you point out except for two:

--COUR_DescriptionCopy_Test & STD_Courses_Test do not seem to have the Description being used in the query as a filter or order by. In the former, Description is indeed part of query but not being used as a filter or order by. In the latter, there aren't even any SOQL queries. Was there another class you were referring to perhaps, or should I be looking into classes referenced by that class.

Similarly in ADDR_HouseholdAcc_TEST I was only able to locate one line where it was used as a filter or order by.

Lastly was there some sort of tool you ran that I can run this through to ensure we got em all, or was this a manual investigation on your part?

**Comment by lifewithryan** [comment]
- Modified unit tests which were using potentially encryptable fields in SOQL filters and order by statements. In most cases they were being used to ensure a specific order was returned. This was mitigated by using a map and then retrieving the records by name. (Since they're unit tests, we can get away with this). This ensures that we can retrieve the objects in a specific order from the map.
- In other cases the ORDER BY clause(s) were not being leveraged by the test code in any manner. In that scenario, the clause was simply removed
- Modified one batch to remove the filter on Description that was checking to see if it Course Description was null. We perform this check in the logic so the filter was redundant.

**Comment by mrbelvedere** [comment]
Included in beta release 1.66 (Beta 2)

**Comment by mrbelvedere** [comment]
Included in production release 1.66
