### ISSUE TITLE
Default Program Plan when creating Program Enrolment

### ISSUE THREAD

**Issue by wdci-dev** [SalesforceFoundation/HEDAP#662]
Hi there,

I noticed that the program plan is no longer be populated automatically when a program enrolment is created. Has this been removed?

**Comment by jacebryan** [comment]
Hi @wdci-dev! When creating a Program Enrollment you have the option to select an existing Program Plan or create a new Program Plan. Are you saying that when you populate the Program Plan field on the Program Enrollment with an existing Program Plan that the Program Plan value is not saving?

**Comment by jacebryan** [comment]
Hi @wdci-dev - I now understand what you are asking about. HEDA does not currently auto populate the Program Plan field on Program Enrollment with the Primary Plan for the associated Academic Program if left blank at the time of creation. If you were experiencing this behavior it may be due to custom automation built in to satisfy this requirement. I would start there. Does this help?

**Comment by jacebryan** [comment]
**lurch: attach W-023785

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x8000000AJrXwAAL" target="_blank">W-023785</a>

**Comment by wdci-dev** [comment]
Hi @jacebryan thanks for the reply. I don't have any customization but I remembered I have tested this before. Maybe I'm looking at the wrong stuff since you have confirmed this feature doesn't exist :)

Any chance that this will be included?

**Comment by jacebryan** [comment]
Hi @wdci-dev - Yes. Our team is currently working to build this functionality into HEDA. No ETA as to when it will be released.

A little background for you: _Usually_ we create a Github Issue for everything that requires work but because this specific ask began as an internal investigation we had yet to create the Issue.

However, since you created an Issue for this feature request (much appreciated!) I felt it would be useful to you, our community, and our team to link your submitted Issue to our internal Work Item (i.e. W-023785) in support of transparency. You can also see that @xinnanlisf has referenced the PR that will close this Issue once it's been merged with the master branch of HEDA which means you will receive a notification once the feature has been released.

Hope all that information helps :)

**Comment by mrbelvedere** [comment]
Included in beta release 1.65 (Beta 3)

**Comment by mrbelvedere** [comment]
Included in production release 1.65

**Comment by jacebryan** [comment]
@wdci-dev - if you follow the [HEDA Release Announcements group in the Power of Us Hub](https://powerofus.force.com/0D51E00004c1O8I) you will see that this enhancement was pushed to Sandboxes on 11/21 and -  if no issues are reported by the HEDA Community - will be pushed to Production instances on 11/27.

**Comment by wdci-dev** [comment]
Hi @jacebryan thanks for the update. I did follow the issue closely and already upgraded HEDA to 1.65. All good!
