### ISSUE TITLE
Access Check Failed error on HEDA Settings. Missing class attribute in CMP_Acc_Naming_Dropdown

### ISSUE THREAD

**Issue by kevinswiggum** [SalesforceFoundation/HEDAP#757]
Bug

If Lighting debug mode is enabled for a user, that user will see the following error at the bottom of the HEDA Settings page

> This page has an error. You might just need to refresh it. Access Check Failed! AttributeSet.get(): attribute 'class' of component 'markup://hed:CMP_Acc_Naming_Dropdown {1150:0}' is not visible to 'markup://aura:if {1152:0}'. Failing descriptor: {aura:if}

The cause is in the CMP_Acc_Naming_Dropdown component. "v.class" is referenced several times in the markup but there is no aura:attribute named "class" defined. The error is getting caught and reported in debug mode, but otherwise you wouldn't see it.

**Comment by kevinswiggum** [comment]
**Lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000008LlpsQAC" target="_blank">W-032060</a>

**Comment by jacebryan** [comment]
**Background:** 

- This issue was reported via Salesforce case escalation on March 20th, 2019. 
- The org in question has both NPSP and HEDA installed.
- The issue may be associated with a known issue that was fixed in Spring 19 related to [Enabling Debug mode for Lightning components](https://success.salesforce.com/issues_view?id=a1p3A000000eaxfQAA) 
- The issue may be due to a bug in the lighting component code.
- @kevinswiggum was able to replicate the error in one of his orgs by turning on Lightning Debug mode. Turning off Debug mode prevents the error.
- Recommendation is for the customer to disable debug mode which will remove the error.

Is there any relation to [Issue 584](https://github.com/SalesforceFoundation/HEDAP/issues/584)?

@aligeez - FYI

**Comment by robertbwatson** [comment]
@jacebryan  & @kevinswiggum  Thanks for all of the helpful information here. This is not related to #584, but it is definitely similar! Fix coming soon :)

**Comment by mrbelvedere** [comment]
Included in beta release 1.74 (Beta 1)

**Comment by mrbelvedere** [comment]
Included in production release 1.74
